#!/usr/bin/env python

dialogue = {'learn_name': ['Hello there, welcome to the University of Cambridge\'s Affective Intelligence and Robotics Lab. What is your name?',
                        'Hi, what is your name?',
                        'Welcome to the lab, can I learn your name?'],
            'after_meeting': ['Nice to meet you, {}!',
                        'I\'m very happy to have a new friend, {}!',
                        'What a nice name {}!'],
            'ask_id': ['Can you please tell me your ID number {}?',
                       '{}, can you share your ID number with me?'],
            'info_saved': ['Thanks, your ID number has been saved.'],
            'get_command': ['{}, would you like to say something?',
                        'Hey, do you want to say anything, {}?',
                        'Dear {}, please say something.'],
            'question': ['{}, can you rate your day out of 3?'],
            'day_rates': ['Sorry to hear that! But don\'t worry, I believe that you can handle it',
                          'Not bad {}, you can make it to 3 after hanging out with your friends!',
                          'That great {}! You must be very happy now!'],
            'not_understood': ['Sorry, I couldn\'t understand your answer. Can you repeat it?'],
            'emotion_not_detected': ['Sorry, I can\'t see your face properly now.'],
            'emotion_detection': ['Let me check you carefully!',
                                  'Face is the reflection of emotions. Let me check yours!'],
            'emotion_happy': ['You look great today {}! What made you so happy?',
                              'You look very happy {}. Can share with me the source of this happiness?',
                              'It is great to see you such happy {}!'],
            'emotion_sad': ['Are you okay {}? You are looking sad. Do you want to share its reason?',
                            'Why are you sad {}? Come on, you should be happy to talk with me!',
                            'You look sad {}. Is everything fine? Would you like to share with me?'],
            'emotion_surprise': ['Gotcha! You are surprised, right?',
                                 'I knew that I am a surprising robot!'],
            'emotion_anger': ['Why are you angry {}? Did I say something wrong?',
                              'Calm down champ! There is no problem.',
                              'Hey, are you okay? Should I worry about myself?'],
            'emotion_disgust': ['Is there something disgusting, {}?',
                                'Why are you looking like there is something disgusting, {}?'],
            'emotion_fear': ['Keep calm {}, there is nothing to fear.',
                             'You look like you afraid of something {}? Is everything okay?'],
            'emotion_neutral': ['You look neutral, just like me!'],
            'goodbye': ['It was nice to meet you {}, take care!',
                        'Hope to see you again, {}, goodbye!',
                        'Have a nice day, {}!',
                        'Thank you for coming {}, see you again!',
                        'Sorry, I couldn\'t understand you. I have to go, see you {}!']}