#!/usr/bin/env python

dialogue = {'learn_name': ['Hello there, welcome to the University of Cambridge\'s Affective Intelligence and Robotics Lab. What is your name?',
                        'Hi, what is your name?',
                        'Welcome to the lab, can I learn your name?'],
            'after_meeting': ['Nice to meet you, {}!',
                        'I\'m very happy to have a new friend, {}!',
                        'What a nice name {}!'],
            'ask_id': ['{}, can you please tell me your ID number?',
                       '{}, can you share your ID number with me?'],
            'info_saved': ['Thanks, your ID number has been saved.'],
            'get_command': ['{}, would you like to say something?',
                        'Hey, do you want to say anything, {}?',
                        'Dear {}, please say something.'],
            'question': ['{}, can you rate your day out of 3?'],
            'day_rates': ['Sorry to hear that! But don\'t worry, I believe that you can handle it',
                          'Not bad {}, you can make it to 3 after hanging out with your friends!',
                          'That great {}! You must be very happy now!'],
            'not_understood': ['Sorry, I couldn\'t understand your answer. Can you repeat it?'],
            'goodbye': ['It was nice to meet you {}, take care!',
                        'Hope to see you again, {}, goodbye!',
                        'Have a nice day, {}!',
                        'Thank you for coming {}, see you again!',
                        'Sorry, I couldn\'t understand you. I have to go, see you {}!']}